version: '3.3'

services:
  postgres_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=quiz_app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
